# Setup
stages:
  - build
  - publish
  - deploy

cache:
  key: "$CI_BUILD_REF_NAME" # Per branch caching
  paths:
    - node_modules

# Job Templates
.template_docker: &template_docker
  tags:
    - docker

.template_docker_privileged: &template_docker_privileged
  tags:
    - docker
    - docker-privileged

.template_node: &template_node
  <<: *template_docker
  image: artifacts.int.corefiling.com:5000/cfl-node:7

.template_python: &template_python
  <<: *template_docker
  image: python:3

# Build stage
## Templates
.template_npm_script: &template_npm_script
  <<: *template_node
  stage: build
  before_script:
    - time yarn install
    - npm config set git-tag-version false
    - npm run set-build-version
    # Caches + Yarn sometimes miss PhantomJS.
    - npm rebuild phantomjs-prebuilt
  script:
    - time npm run $CI_BUILD_NAME

## Jobs
compile:webpack:
  <<: *template_npm_script
  artifacts:
    expire_in: 1 week
    paths:
      - www

test:tslint: *template_npm_script
test:karma: *template_npm_script

# Publish stage
publish:
  <<: *template_docker_privileged
  stage: publish
  image: artifacts.int.corefiling.com:5000/nimbus-tools/build-npm-package:0.5.0-dev.63399
  dependencies:
    - compile:webpack
  # only:
  #   - develop@njlgad/web-ui-starter-kit
  #   - tags@njlgad/web-ui-starter-kit
  variables:
    publish: 'true'
  script:
    - time /app/scripts/build.py

# Deploy stage
.template_deploy: &template_deploy
  <<: *template_python
  stage: deploy
  dependencies:
    - publish
  # only:
  #   - develop@njlgad/web-ui-starter-kit
  #   - tags@njlgad/web-ui-starter-kit
  variables:
    REFRESH_TOKEN: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJiR3F4bm5mMDRud3V2elYwcjhia0hKN0ZtdjRwV1hlRmJpdDE1dkRwNmlrIn0.eyJqdGkiOiI4ZGFhMTkzMS0yY2I0LTQ2NmEtYWY4ZS0zOTg2OTRhNGQ4MTEiLCJleHAiOjAsIm5iZiI6MCwiaWF0IjoxNDkzMzg0MTAxLCJpc3MiOiJodHRwczovL2xvZ2luLmNvcmVmaWxpbmcuY29tL2F1dGgvcmVhbG1zL2t1YmUiLCJhdWQiOiJrdWJlcm5ldGVzIiwic3ViIjoiYzI2ZmFkODEtZDg3Zi00MmE5LWJlNjctYmViYTNhN2MzOTMxIiwidHlwIjoiT2ZmbGluZSIsImF6cCI6Imt1YmVybmV0ZXMiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiI5NDRiNDljMC02OTE2LTRmMzctOTIxMi02YzVlNjQ4YWJlN2EiLCJjbGllbnRfc2Vzc2lvbiI6IjJhMDllZTYwLTY3MjMtNDY2ZS04YWEzLTRkYWRiOTU4NDE1MyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsInZpZXctcHJvZmlsZSJdfX19.IMt9wbULyaFsqN-9-ub7mA4mL8KcX9PhRs5jrRRloez5OKpzD4FLeGMy0RtUZz2qj-1gQpMSave5OqzhmqDdyJ1c2oN9-JQL1v1yhx5ZUspu1XUQcSBWnZzeaE4PWctYymFV_KJxXAR6mryEIkHDgS1Uw7HpG8gnbg2_kx0JrXpL8gb1VhrlNkJQh-SHI8Eh8H7up4fUqsnmJRDikW2dTvxLVOxjqsh4Je8gyclJH0wruI4CwdslCev8paJFojo4C14989RfOi_0j6w-LQTAbNCJzByc-zFhfNn7t15KPL3ft58TXuFN8-4SsP3QjrPAgTmigwtW2_BYozHU6X8Pvw
  before_script:
    - pip3 install pyyaml
    - pip3 install requests
    - curl -LO https://helm.kube.int.corefiling.com/kube-auth
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x kube-auth kubectl
    - mv kube-auth kubectl /usr/local/bin
    - kube-auth login -t $REFRESH_TOKEN
    - if kube-auth namespace list | grep -cq $CI_ENVIRONMENT_SLUG; then echo "namespace $CI_ENVIRONMENT_SLUG already exists"; else kube-auth namespace create $CI_ENVIRONMENT_SLUG; fi;
    - kube-auth namespace use $CI_ENVIRONMENT_SLUG
    - kubectl config get-contexts `kubectl config current-context`
    - kubectl create serviceaccount tiller --namespace=$CI_ENVIRONMENT_SLUG
    - kubectl create rolebinding tiller --clusterrole=cluster-admin --serviceaccount=$CI_ENVIRONMENT_SLUG:tiller --namespace=$CI_ENVIRONMENT_SLUG
    - curl -LO https://storage.googleapis.com/kubernetes-helm/helm-v2.3.1-linux-amd64.tar.gz
    - tar -xzvf /tmp/helm.tar.gz -C /tmp
    - chmod +x /tmp/linux-amd64/helm
    - mv /tmp/linux-amd64/helm /usr/local/bin
    - helm init --tiller-namespace=$CI_ENVIRONMENT_SLUG
    - kubectl get deploy tiller-deploy -o yaml --namespace=$CI_ENVIRONMENT_SLUG > tmp.yaml
    - "sed -i 's/      securityContext: {}/      securityContext: {}\n      serviceAccount: tiller/' tmp.yaml"
    - kubectl apply -f tmp.yaml


deploy:
  <<: *template_deploy
  environment:
    name: $CI_BUILD_REF_NAME
    url: https://$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.kube.int.corefiling.com
    on_stop: deploy:clean
  script:
    - echo "Deploying https://$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.kube.int.corefiling.com"

deploy:clean:
  <<: *template_deploy
  when: manual
  environment:
    name: $CI_BUILD_REF_NAME
    url: https://$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.kube.int.corefiling.com
    action: stop
  script:
    - echo "Pruning https://$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.kube.int.corefiling.com"
