# Setup
stages:
  - build
  - publish
  - deploy

cache:
  key: "$CI_BUILD_REF_NAME" # Per branch caching
  paths:
    - node_modules

# Job Templates
.template_docker: &template_docker
  tags:
    - docker

.template_docker_privileged: &template_docker_privileged
  tags:
    - docker
    - docker-privileged

.template_node: &template_node
  <<: *template_docker
  image: artifacts.int.corefiling.com:5000/cfl-node:7

.template_kube_deploy: &template_kube_deploy
  <<: *template_docker
  image: artifacts.int.corefiling.com:5000/pdds/kube-deploy:0.2


# Build stage
## Templates
.template_npm_script: &template_npm_script
  <<: *template_node
  stage: build
  before_script:
    - time yarn install
    - npm config set git-tag-version false
    - npm run set-build-version
    # Caches + Yarn sometimes miss PhantomJS.
    - npm rebuild phantomjs-prebuilt
  script:
    - time npm run $CI_BUILD_NAME

## Jobs
build:version:
  <<: *template_node
  stage: build
  artifacts:
    expire_in: 1 week
    paths:
      - build.version
  before_script:
    - npm install -g @janslow/ci-build-version@dev
  script:
    - ci-build-version -f package.json > build.version
    - echo `cat build.version`

compile:webpack:
  <<: *template_npm_script
  artifacts:
    expire_in: 1 week
    paths:
      - www

test:tslint: *template_npm_script
test:karma: *template_npm_script


# Publish stage
publish:
  <<: *template_docker_privileged
  stage: publish
  image: artifacts.int.corefiling.com:5000/nimbus-tools/build-npm-package:0.5.0-dev.69735
  dependencies:
    - compile:webpack
  variables:
    publish: 'true'
  script:
    - time /app/scripts/build.py


# Deploy stage
.template_deploy: &template_deploy
  <<: *template_kube_deploy
  stage: deploy
  dependencies:
    - build:version
    - publish
  variables:
    TILLER_NAMESPACE: $CI_ENVIRONMENT_SLUG
  before_script:
    - /kube/init $KUBE_AUTH_TOKEN $CI_ENVIRONMENT_SLUG

deploy:
  <<: *template_deploy
  environment:
    name: $CI_BUILD_REF_NAME
    url: https://$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.kube.int.corefiling.com
    on_stop: deploy:clean
  script:
    - echo "Deploying https://$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.kube.int.corefiling.com"
    - helm upgrade --install --set namespace=$CI_ENVIRONMENT_SLUG,imageTag=`cat build.version` $CI_PROJECT_NAME ./deploy --namespace=$CI_ENVIRONMENT_SLUG

deploy:clean:
  <<: *template_deploy
  when: manual
  environment:
    name: $CI_BUILD_REF_NAME
    url: https://$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.kube.int.corefiling.com
    action: stop
  script:
    - echo "Pruning https://$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.kube.int.corefiling.com"
    - kube-auth namespace delete $CI_ENVIRONMENT_SLUG
