apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}

