apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.global.registry }}/{{ .Values.image }}:{{ .Values.imageTag }}
          imagePullPolicy: {{default "IfNotPresent" .Values.pullPolicy}}
          ports:
            - containerPort: 80
